swagger: "2.0"
info:
  version: 1.0.0
  title: "template1"
  description: Descrizione dell'api
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: nomeapp.herokuapp.com
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /nomeModulo:
    get:
      description: |
        Get all nomeModulo.
      operationId: getallnomeModulo
      responses:
        200:
          description: ritorna tutti gli elementi nomeModulo
          schema:
            type: array
            items:
              $ref: '#/definitions/nomeModulo'
        404:
          description: not found
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Crea un nuovo nomeModulo.  Duplicates are allowed
      operationId: addnomeModulo
      parameters:
        - name: nomeModulo
          in: body
          description: nomeModulo da aggiungere all'array
          required: true
          schema:
            $ref: '#/definitions/NewnomeModulo'
      responses:
        200:
          description: nomeModulo response
          schema:
            $ref: '#/definitions/nomeModulo'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /nomeModulo/{id}:
    get:
      description: ritorna nomeModulo con quel ID
      operationId: getnomeModuloID
      parameters:
        - name: id
          in: path
          description: ID of nomeModulo to fetch
          required: true
          type: string
      responses:
        200:
          description: nomeModulo response
          schema:
            $ref: '#/definitions/nomeModulo'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: deletes a single nomeModulo based on the ID supplied
      operationId: deletenomeModulo
      parameters:
        - name: id
          in: path
          description: ID of nomeModulo to delete
          required: true
          type: string
      responses:
        200:
          description: nomeModulo deleted
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    put:
      description: put a single nomeModulo based on the ID supplied
      operationId: putnomeModulo
      parameters:
        - name: id
          in: path
          description: ID of nomeModulo to modify
          required: true
          type: string
      responses:
        200:
          description: nomeModulo modified
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  nomeModulo:
    allOf:
      - $ref: '#/definitions/NewnomeModulo'
      - properties:
          id:
            type: string
  NewnomeModulo:
    required:
      - attributo1
      - attributo2
      - attributo3
    properties:
      attributo1:
        type: string
      attributo2:
        type: string
      attributo3:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string